python app.py Testor LayerTestor attack_diff %3 %1 %2 %4
python app.py Testor LayerTestor attack_imbalance %3 %1 %2 %4
python app.py Testor LayerTestor down_attack %3 %1 %2 %4
python app.py Testor LayerTestor down_attack_on_down %3 %1 %2 %4
python app.py Testor LayerTestor down_attack_ratio %3 %1 %2 %4
python app.py Testor LayerTestor down_defense %3 %1 %2 %4
python app.py Testor LayerTestor down_defense_ratio %3 %1 %2 %4
python app.py Testor LayerTestor down_power %3 %1 %2 %4
python app.py Testor LayerTestor down_power_ratio %3 %1 %2 %4
python app.py Testor LayerTestor up_attack %3 %1 %2 %4
python app.py Testor LayerTestor up_attack_on_up %3 %1 %2 %4
python app.py Testor LayerTestor up_attack_ratio %3 %1 %2 %4
python app.py Testor LayerTestor up_defense %3 %1 %2 %4
python app.py Testor LayerTestor up_defense_ratio %3 %1 %2 %4
python app.py Testor LayerTestor up_power %3 %1 %2 %4
python app.py Testor LayerTestor up_power_ratio %3 %1 %2 %4
